<table class="table table-striped table-hover">
<thead>
  <tr>
    <th width="15%" class="text-center">Avatar</th>
    <th width="20%" class="text-left">Full Name</th>
    <th width="25%" class="text-left">Email</th>
    <th width="10%" class="text-center">Role</th>
    <th width="8%" class="text-center">Status</th>
    <th width="14%" class="text-center">Last Login</th>
    <th width="8%" class="text-center">Actions</th>
  </tr>
</thead>
<tbody>
<?php if (empty($this->users)):?>
  <tr>
    <td colspan="7" class="text-center">No records</td>
  </tr>
<?php else:?>
  <?php foreach ($this->users as $user):?>
    <tr>
      <td class="text-center"><img src="<?=$user->avatar?>"></td>
      <td class="text-left"><?=$user->full_name?></td>
      <td class="text-left"><?=$user->email?></td>
      <td class="text-center"><?=$user->role?></td>
      <td class="text-center"><?=$user->status?></td>
      <td class="text-center"><?=convertToDateDisplay($user->last_login, true)?></td>
      <td class="text-center">
      <?php if ($this->layout()->loggedUser->id != $user->id):?>
        <a href="javascript:editUser(<?=$user->id?>);" title="<?=$this->layout()->translator->getLang('tooltip_edit')?>"><i class="fas fa-pencil-alt text-blue"></i></a>
        &nbsp;
        <a href="javascript:deleteUser(<?=$user->id?>);" title="<?=$this->layout()->translator->getLang('tooltip_delete')?>"><i class="far fa-trash-alt text-red"></i></a>
      <?php endif;?>
      </td>
    </tr>
  <?php endforeach;?>
<?php endif;?>
</tbody>
</table>

<?php
if (isset($this->paginator) && $this->paginator->getTotalItemCount() > $this->paginator->getItemCountPerPage()):
  $from = ($this->paginator->getCurrentPageNumber() - 1)*$this->paginator->getItemCountPerPage() + 1;
  $to = $this->paginator->getCurrentPageNumber()*$this->paginator->getItemCountPerPage();
  if ($to > $this->paginator->getTotalItemCount()) {
    $to = $this->paginator->getTotalItemCount();
  }
?>
  <!--Paginator-->
  <div class="paginator">
    <div class="float-left text-blue">
      <?=$from?> - <?=$to?> of <?=$this->paginator->getTotalItemCount()?>
    </div>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', ['route' => '/', 'ajaxFunc' => 'getUsers']) ?>
  </div>
<?php endif; ?>