<?php $midRange = 4; ?>
<nav aria-label="Page navigation" class="float-right">
    <ul class="pagination pagination-circle pg-unique">
      <!-- Previous page link -->
      <?php if (isset($this->previous)): ?>
          <li class="page-item">
              <a class="page-link" aria-label="Previous" href="<?= empty($this->ajaxFunc) ? $this->url($this->route, [], ['query' => ['page' => $this->previous]]) : 'javascript: '.$this->ajaxFunc.'('.$this->previous.')'; ?>">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Previous</span>
              </a>
          </li>
      <?php else: ?>
          <li class="page-item disabled">
              <a class="page-link" aria-label="Previous" href="#">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Previous</span>
              </a>
          </li>
      <?php endif ?>

      <!-- Numbered page links -->
      <li class="page-item<?php if ($this->current == 1): ?> active<?php endif;?>">
        <a class="page-link" href="<?php if ($this->current == 1): ?>javascript:void(0);<?php else:?><?= empty($this->ajaxFunc) ? $this->url($this->route, [], ['query' => ['page' => 1]]) : 'javascript: '.$this->ajaxFunc.'(1)'; ?><?php endif;?>">1</a>
      </li>

      <?php if ($this->current > $midRange+1): ?>
        <li class="page-item disabled">
          <a class="page-link" href="#">...</a>
        </li>
      <?php endif ?>

        <?php foreach ($this->pagesInRange as $page): ?>
          <?php if ($page != 1 && $page != $this->pageCount && $this->current - $midRange < $page && $page < $this->current + $midRange): ?>
            <li class="page-item<?php if ($page == $this->current): ?> active<?php endif;?>">
              <a class="page-link" href="<?php if ($page == $this->current): ?>javascript:void(0);<?php else: ?><?= empty($this->ajaxFunc) ? $this->url($this->route, [], ['query' => ['page' => $page]]) : 'javascript: '.$this->ajaxFunc.'('.$page.')';?><?php endif;?>">
                <?= $page ?>
              </a>
            </li>
          <?php endif ?>
        <?php endforeach ?>

      <?php if ($this->current < $this->pageCount - $midRange): ?>
        <li class="page-item disabled">
          <a class="page-link" href="#">...</a>
        </li>
      <?php endif ?>

      <?php if ($this->pageCount > 1):?>
      <li class="page-item<?php if ($this->current == $this->pageCount): ?> active<?php endif;?>">
        <a class="page-link" href="<?php if ($this->current == $this->pageCount): ?>javascript:void(0);<?php else:?><?= empty($this->ajaxFunc) ? $this->url($this->route, [], ['query' => ['page' => $this->pageCount]]) : 'javascript: '.$this->ajaxFunc.'('.$this->pageCount.')'; ?><?php endif;?>"><?=$this->pageCount?></a>
      </li>
      <?php endif;?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li class="page-item">
                <a class="page-link" aria-label="Next" href="<?= empty($this->ajaxFunc) ? $this->url($this->route, [], ['query' => ['page' => $this->next]]) : 'javascript: '.$this->ajaxFunc.'('.$this->next.')'; ?>">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        <?php else: ?>
            <li class="page-item disabled">
                <a class="page-link" aria-label="Next" href="#">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        <?php endif ?>
    </ul>
</nav>