<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title text-uppercase">Xác nhận đơn hàng</h4>
      <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <form id="transactionForm" action="#">
        <input type="hidden" name="cartProductStr" value='<?=$this->cartProductStr?>'>
        <div class="row">
          <div class="col-md-6 mb-4"><b><label>Tổng số lượng:</label> <span class="text-green"><?=$this->totalQuantity?></span></b></div>
          <div class="col-md-6 mb-4 text-end"><b><label>Tổng tiền:</label> <span class="text-green"><?=formatNumber($this->totalAmount)?> VND</span></b></div>
        </div>
        <div class="row">
          <div class="col-md-4 mb-4">
            <label class="form-label required" for="contactInfo">Người nhận hàng</label>
            <input class="form-control" id="contactInfo" name="contactInfo" type="text" required>
          </div>
          <div class="col-md-8 mb-4">
            <label class="form-label required" for="deliverPlace">Địa chỉ giao hàng</label>
            <input class="form-control" id="deliverPlace" name="deliverPlace" type="text" required>
          </div>
          <div class="col-md-12 mb-3">
            <label class="form-label" for="notes">Ghi chú</label>
            <textarea class="form-control" id="notes" name="notes" rows="4"></textarea>
          </div>
          <div class="col-md-12 text-center">
            <button id="btnSave" class="btn btn-outline-primary"><i class="far fa-save me-2"></i>Xác nhận</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
