<h2 class="lined lined-center text-uppercase text-green mb-4">Giao dịch thành công</h2>
<div class="space"></div>
<hr>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="row">
  <div class="col-md-12 text-center">
    Bạn vừa thanh toán thành công. Chúng tôi sẽ liên hệ bạn trong thời gian sớm nhất. Trở lại <a href="/">Trang chủ</a>
  </div>
</div>

<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
<div class="space"></div>
