<!-- HEADING BREADCRUMB-->
<section class="bg-pentagon py-4">
  <div class="container py-3">
    <div class="row d-flex align-items-center gy-4">
      <div class="col-md-7">
        <h1 class="h2 mb-0 text-uppercase">Giới thiệu</h1>
      </div>
      <div class="col-md-5">
        <!-- Breadcrumb-->
        <ol class="text-sm justify-content-start justify-content-lg-end mb-0 breadcrumb undefined">
          <li class="breadcrumb-item"><a class="text-uppercase" href="/">Trang chủ</a></li>
          <li class="breadcrumb-item text-uppercase active">Giới thiệu</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- TEAM SECTION-->
<section class="py-5">
  <div class="container py-4">
    <header class="mb-5">
      <h2 class="text-uppercase lined mb-4">Chúng tôi là ai?</h2>
      <p class="lead">Chúng tôi là những thành viên luôn nâng cao nhu cầu của khách hàng lên hàng đầu.</p>
    </header>
    <div class="mb-5">
      <div class="row gy-4">
        <!-- Team member  -->
        <div class="col-lg-3 col-md-6 text-center"><a href="team-member.html"><img class="avatar avatar-xxl p-2 mb-4" src="img/person-1.jpg" alt="Rosemary"></a>
          <h3 class="h4 mb-1 text-uppercase"><a class="text-reset" href="team-member.html">Rosemary</a></h3>
          <p class="text-muted small text-uppercase">Trưởng bộ phận CSKH</p>
        </div>
        <!-- Team member  -->
        <div class="col-lg-3 col-md-6 text-center"><a href="team-member.html"><img class="avatar avatar-xxl p-2 mb-4" src="img/person-2.png" alt="Nancy"></a>
          <h3 class="h4 mb-1 text-uppercase"><a class="text-reset" href="team-member.html">Nancy</a></h3>
          <p class="text-muted small text-uppercase">Trưởng bộ phận Marketing</p>
        </div>
        <!-- Team member  -->
        <div class="col-lg-3 col-md-6 text-center"><a href="team-member.html"><img class="avatar avatar-xxl p-2 mb-4" src="img/person-3.png" alt="Neil"></a>
          <h3 class="h4 mb-1 text-uppercase"><a class="text-reset" href="team-member.html">Neil</a></h3>
          <p class="text-muted small text-uppercase">Trưởng bộ phận Kinh doanh</p>
        </div>
        <!-- Team member  -->
        <div class="col-lg-3 col-md-6 text-center"><a href="team-member.html"><img class="avatar avatar-xxl p-2 mb-4" src="img/person-4.png" alt="Percy"></a>
          <h3 class="h4 mb-1 text-uppercase"><a class="text-reset" href="team-member.html">Percy</a></h3>
          <p class="text-muted small text-uppercase">Nhà sáng lập</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- TESTIMONIALS SECTION-->
<section class="py-5 bg-gray-200">
  <div class="container py-4">
    <header class="mb-5">
      <h2 class="lined lined-center text-uppercase mb-4">Khách hàng nói gì về chúng tôi</h2>
      <p class="lead text-center">Chúng tôi luôn thỏa mãn mọi nhu cầu của khách hàng với các dòng sản phẩm sang xịn đẹp.</p>
    </header>
    <!-- Testimonials slider-->
    <div class="swiper-container testimonials-slider">
      <div class="swiper-wrapper">
        <div class="swiper-slide h-auto mb-5">
          <div class="p-4 bg-white h-100 d-flex flex-column justify-content-between">
            <div class="mb-2">
              <p class="text-sm text-gray-600">Nữ giám đốc kính cận dễ thương quá trời.</p>
              <p class="text-sm text-gray-600"></p>
            </div>
            <div class="d-flex align-items-center justify-content-between"><i class="fas fa-quote-left text-primary fa-2x"></i>
              <div class="d-flex align-items-center ms-3">
                <div class="me-3 text-end">
                  <h5 class="text-uppercase mb-0">Kevin Huynh</h5>
                  <p class="small text-muted mb-0">Technical Director, Husol</p>
                </div><img class="avatar p-1 flex-shrink-0" src="img/cto.jpg" alt="Kevin" width="60">
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide h-auto mb-5">
          <div class="p-4 bg-white h-100 d-flex flex-column justify-content-between">
            <div class="mb-2">
              <p class="text-sm text-gray-600">The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. &quot;What's happened to me? &quot; he thought. It wasn't a dream.</p>
              <p class="text-sm text-gray-600"></p>
            </div>
            <div class="d-flex align-items-center justify-content-between"><i class="fas fa-quote-left text-primary fa-2x"></i>
              <div class="d-flex align-items-center ms-3">
                <div class="me-3 text-end">
                  <h5 class="text-uppercase mb-0">Nancy</h5>
                  <p class="small text-muted mb-0">Technical Business Analyst, Husol</p>
                </div><img class="avatar p-1 flex-shrink-0" src="img/person-2.png" alt="John McIntyre" width="60">
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide h-auto mb-5">
          <div class="p-4 bg-white h-100 d-flex flex-column justify-content-between">
            <div class="mb-2">
              <p class="text-sm text-gray-600">His room, a proper human room although a little too small, lay peacefully between its four familiar walls.</p>
              <p class="text-sm text-gray-600">A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.</p>
            </div>
            <div class="d-flex align-items-center justify-content-between"><i class="fas fa-quote-left text-primary fa-2x"></i>
              <div class="d-flex align-items-center ms-3">
                <div class="me-3 text-end">
                  <h5 class="text-uppercase mb-0">Rosemary</h5>
                  <p class="small text-muted mb-0">Designer, Husol</p>
                </div><img class="avatar p-1 flex-shrink-0" src="img/person-1.jpg" alt="John McIntyre" width="60">
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide h-auto mb-5">
          <div class="p-4 bg-white h-100 d-flex flex-column justify-content-between">
            <div class="mb-2">
              <p class="text-sm text-gray-600">It showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look out the window at the dull weather. Drops of rain could be heard hitting the pane, which made him feel quite sad. Gregor then turned to look out the window at the dull weather. Drops of rain could be heard hitting the pane, which made him feel quite sad.</p>
              <p class="text-sm text-gray-600"></p>
            </div>
            <div class="d-flex align-items-center justify-content-between"><i class="fas fa-quote-left text-primary fa-2x"></i>
              <div class="d-flex align-items-center ms-3">
                <div class="me-3 text-end">
                  <h5 class="text-uppercase mb-0">Harris</h5>
                  <p class="small text-muted mb-0">DevOps, Husol</p>
                </div><img class="avatar p-1 flex-shrink-0" src="img/devops.png" alt="John McIntyre" width="60">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
</section>
