<!-- HEADING BREADCRUMB-->
<section class="bg-pentagon py-4">
  <div class="container py-3">
    <div class="row d-flex align-items-center gy-4">
      <div class="col-md-7">
        <h1 class="h2 mb-0 text-uppercase">Tin tức</h1>
      </div>
      <div class="col-md-5">
        <!-- Breadcrumb-->
        <ol class="text-sm justify-content-start justify-content-lg-end mb-0 breadcrumb undefined">
          <li class="breadcrumb-item"><a class="text-uppercase" href="/">Trang chủ</a></li>
          <li class="breadcrumb-item text-uppercase active">Tin tức</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- BLOG SECTION-->
<section class="py-5">
  <div class="container py-4">
    <div class="row gy-5">
      <div class="col-lg-12">
        <ul class="list-unstyled">
          <?php foreach ($this->newses as $news):?>
          <li class="mb-4">
            <h3><a target="_blank" href="<?=$news['link']?>"><?=$news['title']?></a></h3>
            <span>Đăng vào: <?=convertToDateDisplay($news['pubDate'], true)?></span>
            <div><?=$news['desc']?></div>
          </li>
          <?php endforeach;?>
        </ul>
      </div>
    </div>
  </div>
