<div class="body">
  <div class="content" style="margin: 5%; margin-top: 2%;">
    <div class="page-inner">
      <div class="row">
        <div class="col-md-8">
          <?php if ($this->result['status']):?>
            <h3>
              <span class="loadingText text-green">Tài khoản của bạn vừa được kích hoạt thành công. Tự động chuyển đến trang <a href="/sign-in">Đăng nhập</a> sau <span id="countdown">7</span> seconds</span>
            </h3>
          <?php else:?>
          <h3 class="text-red">Error: <span class="text-red"><?=$this->result['message']?></span></h3>
          <?php endif;?>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  // Total seconds to wait
  var seconds = 7;

  function countdown() {
    seconds = seconds - 1;
    if (seconds < 0) {
      // Change your redirection link here
      window.location = root_url + "sign-in";
    } else {
      // Update remaining seconds
      document.getElementById("countdown").innerHTML = seconds;
      // Count down using javascript
      window.setTimeout("countdown()", 1000);
    }
  }

  // Run countdown function
  countdown();

</script>

