<div class="modal-dialog modal-md" role="document">
  <!--Content-->
  <div class="modal-content">

    <!--Header-->
    <div class="modal-header bg-blue text-white">
      <h4>Quên mật khẩu?</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <!--Body-->
    <div class="modal-body mb-0">

      <form id="formForgotPassword" class="eventEnterKey" data-enterkey="btnSubmit" novalidate>
        <div class="row">
          <div class="form-group label-float col-md-12">
            <label for="email" class="required">Email đã đăng ký tài khoản</label>
            <input type="text" id="email" name="email" placeholder="Nhập email" class="form-control" required>
            <div class="invalid-feedback">Sai email</div>
          </div>
        </div>
      </form>
    </div>
    <div class="modal-footer justify-content-center">
      <button id="btnSubmit" class="btn btn-primary"><?=$this->layout()->translator->getLang('btn_submit')?></button>
    </div>
  </div>
  <!--/.Content-->
</div>