<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title text-uppercase">Đăng nhập</h4>
      <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <form id="loginForm">
        <div class="form-group mb-3">
          <input class="form-control" id="email" name="email" type="text" placeholder="Email" required>
        </div>
        <div class="form-group mb-3">
          <input class="form-control" id="password" name="password" type="password" placeholder="Mật khẩu" required>
        </div>
        <p class="text-center">
          <button id="btnLogin" class="btn btn-outline-primary"><i class="fas fa-door-open"></i> Đăng nhập</button>
        </p>
      </form>
    </div>
  </div>
</div>
