<!-- HEADING BREADCRUMB-->
<section class="bg-pentagon py-4">
  <div class="container py-3">
    <div class="row d-flex align-items-center gy-4">
      <div class="col-md-7">
        <h1 class="h2 mb-0 text-uppercase">Đăng ký tài khoản mới</h1>
      </div>
      <div class="col-md-5">
        <!-- Breadcrumb-->
        <ol class="text-sm justify-content-start justify-content-lg-end mb-0 breadcrumb undefined">
          <li class="breadcrumb-item"><a class="text-uppercase" href="/">Home</a></li>
          <li class="breadcrumb-item text-uppercase active">Đăng ký tài khoản mới</li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="py-5">
  <div class="container py-4">
    <div class="row g-5">
      <!-- REGISTER BLOCK-->
      <div class="col-lg-12">
        <header class="mb-5">
          <h2 class="text-uppercase mb-4">Tạo tài khoản</h2>
          <p class="lead">Bạn chưa từng là khách hàng của chúng tôi?</p>
        </header>
        <p>Vui lòng điền chính xác thông tin đăng ký tài khoản, sau đó kích hoạt tài khoản từ email của bạn.</p>
        <p class="text-muted mb-4">Nêu có bất cứ thắc mắc nào, vui lòng đừng e ngại <a href="/contact">liên lạc với chúng tôi</a>, bộ phận chăm sóc khác hàng của chung tôi làm việc 24/7.</p>
        <hr class="border-gray-200">
        <!-- REGISTER FORM-->
        <form id="formRegister">
          <div class="row">
            <div class="form-group col-md-3 mb-3">
              <label class="form-label required" for="fullName">Họ và tên</label>
              <input class="form-control" id="fullName" type="text" name="fullName" placeholder="Nhập họ và tên của bạn" required>
            </div>
            <div class="form-group col-md-3 mb-3">
              <label class="form-label required" for="mobile">Số điện thoại</label>
              <input class="form-control" id="mobile" type="text" name="mobile" placeholder="Nhập số điện thoại của bạn" required>
            </div>
            <div class="form-group col-md-6 mb-3">
              <label class="form-label" for="address">Địa chỉ</label>
              <input class="form-control" id="address" type="text" name="address" placeholder="Nhập địa chỉ của bạn">
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-6 mb-3">
              <label class="form-label required" for="email">Email</label>
              <input class="form-control" id="email" type="text" name="email" placeholder="Nhập email của bạn" required>
            </div>
            <div class="form-group col-md-3 mb-3">
              <label class="form-label required" for="password">Mật khẩu</label>
              <input class="form-control" id="password" type="password" name="password" placeholder="Nhập mật khẩu bạn mong muốn">
            </div>
            <div class="form-group col-md-3 mb-3">
              <label class="form-label required" for="confirmPassword">Nhập lại khẩu</label>
              <input class="form-control" id="confirmPassword" type="password" name="confirmPassword" placeholder="Nhập lại mật khẩu">
            </div>
          </div>
          <br>
          <div class="form-group mb-3 text-center">
            <button id="btnRegister" class="btn btn-outline-primary"><i class="fas fa-user me-2"></i>Đăng ký</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

<script src="https://www.google.com/recaptcha/api.js?render=<?=$this->captchaSiteKey?>"></script>
<?php $this->inlineScript()->prependFile($this->basePath("js/modules/auth.{$this->layout()->dateVersion}.js")) ?>

