<div class="body">
  <div class="content" style="margin: 5%; margin-top: 2%;">
    <div class="page-inner">
      <div class="row">
        <div class="col-md-8">
          <div class="header">
            <div>Hus<span>Laminas</span></div>
            <br>
          </div>
          <div style="position:absolute; top:50%; left:30%">
            <h2 class="text-muted pb-2 fw-bold">Manage your website right now!</h2>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <div class="card-header card-secondary">
              <div class="card-head-row">
                <div class="card-title">Thông tin Thay Đổi Mật Khẩu</div>
              </div>
            </div>
            <div class="card-body">
              <form id="changePasswordForm" class="eventEnterKey" data-enterkey="btnChangePassword">
                <div class="form-group label-float">
                  <label for="email" class="required">Email</label>
                  <input type="email" id="email" class="form-control" placeholder="Email" name="email" value="<?=$this->email?>" required>
                  <div class="invalid-feedback">Sai Email</div>
                </div>
                <div class="form-group label-float">
                  <label for="newPassword" class="required">Mật khẩu mới</label>
                  <input type="password" id="newPassword" class="form-control" placeholder="Nhập mật khẩu" minlength="8" name="newPassword" required>
                  <div class="invalid-feedback">Mật khẩu phải có ít nhất 8 ký tự</div>
                </div>
                <div class="form-group label-float">
                  <label for="confirmPassword">Nhập lại mật khẩu</label>
                  <input type="password" id="confirmPassword" class="form-control" placeholder="Nhập lại mật khẩu" name="confirmPassword">
                </div>
                <input type="hidden" name="token" value="<?=$this->token?>" />
              </form>
            </div>
            <div class="card-action text-center">
              <button id="btnChangePassword" class="btn btn-primary"><i class="fas fa-exchange-alt"></i> Đổi mật khẩu</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

