<table class="table table-striped table-hover">
<thead>
  <tr>
    <th width="10%" class="text-right">Mã giao dịch</th>
    <th width="10%" class="text-left">Họ tên người dùng</th>
    <th width="10%" class="text-left">Số điện thoại liên hệ</th>
    <th width="12%" class="text-left">Thông tin người nhận hàng</th>
    <th width="20%" class="text-left">Địa điểm giao hàng</th>
    <th width="20%" class="text-left">Ghi chú</th>
    <th width="10%" class="text-right">Tổng tiền</th>
    <th width="8%" class="text-center">Trạng thái</th>
  </tr>
</thead>
<tbody>
<?php if (empty($this->transactions)):?>
  <tr>
    <td colspan="7" class="text-center">Không có giao dịch nào.</td>
  </tr>
<?php else:?>
  <?php foreach ($this->transactions as $transaction):?>
    <tr class="transaction cursor-pointer <?=$transaction->colorClass?>" data-id="<?=$transaction->id?>">
      <td class="text-right">#<?=$transaction->id?></td>
      <td class="text-left"><?=$transaction->userFullName?></td>
      <td class="text-left"><?=$transaction->userMobile?></td>
      <td class="text-left"><?=$transaction->contact_info?></td>
      <td class="text-left"><?=$transaction->deliver_place?></td>
      <td class="text-left"><?=$transaction->notes?></td>
      <td class="text-right"><?=formatNumber($transaction->amount)?></td>
      <td class="text-center">
        <select onchange="updateStatus(<?=$transaction->id?>, this.value);">
          <option value="0"<?=$transaction->status == 0 ? ' selected' : ''?>>PENDING</option>
          <option value="1"<?=$transaction->status == 1 ? ' selected' : ''?>>DELIVERING</option>
          <option value="2"<?=$transaction->status == 2 ? ' selected' : ''?>>CANCELED</option>
          <option value="3"<?=$transaction->status == 3 ? ' selected' : ''?>>COMPLETED</option>
        </select>
      </td>
    </tr>
  <?php endforeach;?>
<?php endif;?>
</tbody>
</table>

<?php
if (isset($this->paginator) && $this->paginator->getTotalItemCount() > $this->paginator->getItemCountPerPage()):
  $from = ($this->paginator->getCurrentPageNumber() - 1)*$this->paginator->getItemCountPerPage() + 1;
  $to = $this->paginator->getCurrentPageNumber()*$this->paginator->getItemCountPerPage();
  if ($to > $this->paginator->getTotalItemCount()) {
    $to = $this->paginator->getTotalItemCount();
  }
?>
  <!--Paginator-->
  <div class="paginator">
    <div class="float-left text-blue">
      <?=$from?> - <?=$to?> of <?=$this->paginator->getTotalItemCount()?>
    </div>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', ['route' => '/', 'ajaxFunc' => 'getContacts']) ?>
  </div>
<?php endif; ?>
