<div class="modal-dialog modal-lg" role="document">
  <!--Content-->
  <div class="modal-content">
    <!--Header-->
    <div class="modal-header bg-blue text-white">
      <h3>Chi tiết giao dịch</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <!--Body-->
    <div class="modal-body mb-0">
      <table class="table table-striped table-hover">
        <thead>
        <tr>
          <th width="10%" class="text-right">STT</th>
          <th width="40%" class="text-left">Sản phẩm</th>
          <th width="20%" class="text-right">Số lượng</th>
          <th width="30%" class="text-right">Thành tiền</th>
        </tr>
        </thead>
        <tbody>
        <?php if (empty($this->orders)):?>
          <tr>
            <td colspan="4" class="text-center">Không có sản phẩm nào.</td>
          </tr>
        <?php else:?>
          <?php $totalAmount = 0; ?>
          <?php foreach ($this->orders as $index => $order):?>
            <tr>
              <td class="text-right"><?=$index + 1?></td>
              <td class="text-left"><?=$order->productName?></td>
              <td class="text-right"><?=$order->quantity?></td>
              <td class="text-right"><?=formatNumber($order->amount)?> VND</td>
            </tr>
          <?php $totalAmount += $order->amount?>
          <?php endforeach;?>
          <tr>
            <td class="text-right" colspan="3"><b>Tổng cộng</b></td>
            <td class="text-right"><b><?=formatNumber($totalAmount)?> VND</b></td>
          </tr>
        <?php endif;?>
        </tbody>
      </table>
    </div>

    <div class="modal-footer justify-content-center">
      <button class="btn btn-primary" data-dismiss="modal" aria-label="Close">OK</button>
    </div>
  </div>
  <!--/.Content-->
</div>
