<?= $this->doctype() ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="shortcut icon" href="<?=$this->basePath("/img/favicon.ico")?>" type="image/x-icon">
  <?php $appName = $this->layout()->isLive ? 'Hus Laminas' : 'BETA Hus Laminas';?>
  <?= $this->headTitle("{$appName} {$this->layout()->appVersion}")->setSeparator(' - ')->setAutoEscape(false) ?>

  <?= $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Styles -->
  <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ->prependStylesheet($this->basePath("css/style.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/hus.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/toastr.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/jquery-ui-1.12.1.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/atlantis.min.{$this->layout()->dateVersion}.css"))
    ->prependStylesheet($this->basePath("css/bootstrap-4.4.1.min.{$this->layout()->dateVersion}.css"))
  ?>

  <!-- Scripts -->
  <?= $this->headScript()
    ->prependFile($this->basePath("js/hus.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/autoNumeric.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/atlantis.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery.mask-1.7.7.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/toastr.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/bootstrap-select.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery.serializejson.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery-ui-1.12.1.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/bootstrap-4.4.1.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/popper.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/jquery-3.4.1.min.{$this->layout()->dateVersion}.js"))
    ->prependFile($this->basePath("js/webfont.min.{$this->layout()->dateVersion}.js"))
  ?>

  <style>
    .body{
      position: absolute;
      top: 0px;
      left: 0px;
      right: -40px;
      bottom: -40px;
      width: 100%;
      height: 100%;
      background-image:    url('<?=$this->basePath('img/bg-login.jpg')?>');
      background-size:     cover;
      background-repeat:   no-repeat;
      background-position: center center;
      overflow: hidden;
    }

    .grad{
      position: absolute;
      top: -20px;
      left: -20px;
      right: -40px;
      bottom: -40px;
      width: auto;
      height: auto;
      background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
      z-index: 1;
      opacity: 0.7;
    }

    .header{
      position: absolute;
      top: calc(50% - 35px);
      left: calc(50% - 255px);
      z-index: 2;
    }

    .header div{
      float: left;
      color: #fff;
      font-family: 'Exo', sans-serif;
      font-size: 35px;
      font-weight: 400;
    }

    .header div span{
      color: #5379fa !important;
    }

    .login{
      position: absolute;
      top: calc(50% - 75px);
      left: calc(50% - 50px);
      height: 150px;
      width: 350px;
      padding: 10px;
      z-index: 2;
    }

    .login input[type=email]{
      width: 250px;
      height: 30px;
      background: transparent;
      border: 1px solid #fff;
      border-radius: 2px;
      color: #fff;
      font-family: 'Exo', sans-serif;
      font-size: 16px;
      font-weight: 600;
      padding: 4px;
    }

    .login input[type=password]{
      width: 250px;
      height: 30px;
      background: transparent;
      border: 1px solid #fff;
      border-radius: 2px;
      color: #fff;
      font-family: 'Exo', sans-serif;
      font-size: 16px;
      font-weight: 600;
      padding: 4px;
      margin-top: 10px;
    }

    .login button {
      width: 260px;
      height: 35px;
      background: #fff;
      border: 1px solid #fff;
      cursor: pointer;
      border-radius: 2px;
      color: #43a107;
      font-family: 'Exo', sans-serif;
      font-size: 16px;
      font-weight: 400;
      padding: 6px;
      margin-top: 10px;
    }

    .login button:hover{
      opacity: 0.8;
    }

    .login button:active{
      opacity: 0.6;
    }

    .login button:focus{
      outline: none;
      border: 1px solid rgba(255,255,255,0.9);
    }

    .login input[type=password]:focus{
      outline: none;
      border: 1px solid rgba(255,255,255,0.9);
    }

    .login button:focus{
      outline: none;
    }

    ::placeholder {
      color: white;
    }
    ::-webkit-input-placeholder {
      color: white;
    }

    ::-moz-input-placeholder {
      color: white;
    }
  </style>

  <script>
    WebFont.load({
      google: {"families":["Lato:300,400,700,900"]},
      custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['<?=$this->basePath("css/fonts.min.{$this->layout()->dateVersion}.css")?>']},
      active: function() {
        sessionStorage.fonts = true;
      }
    });
  </script>
</head>

<body>
<?=$this->render('js_variables.phtml')?>
<!-- The Modal -->
<div id="commonDialog" class="modal fade" role="dialog" tabindex="-1"></div>

<?= $this->content ?>

<!--Footer-->
<footer class="page-footer pt-0 mdb-color lighten-4 fixed-bottom">
  <!--Copyright-->
  <div class="text-white py-3 text-center">
    <div class="container-fluid">© <?= date('Y')?> Copyright by <a class="text-white" href="https://husol.org" target="_blank"> Husol.org</a></div>
  </div>
  <!--/.Copyright-->
</footer>
<!--/.Footer-->

<div id="loading" class="notification_box">
  <p><span id="infoText">Processing...</span></p>
  <i class="fas fa-spinner fa-pulse text-dark mt-1 float-right"></i>
</div>

<?= $this->inlineScript()
  ->prependFile($this->basePath("js/common.{$this->layout()->dateVersion}.js"))
?>
</body>
</html>
