<nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">

  <div class="container-fluid">
    <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
      <li class="nav-item toggle-nav-search hidden-caret">
        <a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
          <i class="fa fa-search"></i>
        </a>
      </li>
      <li class="nav-item dropdown hidden-caret">
        <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
          <div class="avatar-sm">
            <img src="https://ui-avatars.com/api/?name=<?=$this->layout()->loggedUser->full_name?>" alt="avatar" class="avatar-img rounded-circle">
          </div>
        </a>
        <ul class="dropdown-menu dropdown-user animated fadeIn">
          <div class="dropdown-user-scroll scrollbar-outer">
            <li>
              <div class="user-box">
                <div class="avatar-lg"><img src="https://ui-avatars.com/api/?name=<?=$this->layout()->loggedUser->full_name?>" alt="avatar" class="avatar-img rounded"></div>
                <div class="u-text">
                  <h4><?=$this->layout()->loggedUser->full_name?></h4>
                  <p class="text-muted"><?=$this->layout()->loggedUser->email?></p><a href="javascript:updateMyAccount();" class="btn btn-xs btn-secondary btn-sm">My Account</a>
                </div>
              </div>
            </li>
            <li class="text-center">
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/sign-out">Logout</a>
            </li>
          </div>
        </ul>
      </li>
    </ul>
  </div>
</nav>