<div class="sidebar sidebar-style-2">
  <div class="sidebar-wrapper scrollbar scrollbar-inner">
    <div class="sidebar-content">
      <div class="user">
        <div class="avatar-sm float-left mr-2">
          <img src="https://ui-avatars.com/api/?name=<?=$this->layout()->loggedUser->full_name?>" alt="avatar" class="avatar-img rounded-circle">
        </div>
        <div class="info">
          <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
								<span>
                  <?=$this->layout()->loggedUser->full_name?>
                  <span class="user-level">
                    <?php switch ($this->layout()->loggedUser->role):
                    case ROLE_STAFF: echo "STAFF"; break;
                    case ROLE_ADMIN: echo "ADMIN"; break;
                    endswitch;?>
                  </span>
									<span class="caret"></span>
								</span>
          </a>
          <div class="clearfix"></div>

          <div class="collapse in" id="collapseExample">
            <ul class="nav">
              <li>
                <a href="javascript:updateMyAccount();">
                  <span class="link-collapse">Tài khoản của bạn</span>
                </a>
              </li>
              <li>
                <a href="/sign-out">
                  <span class="link-collapse">Đăng xuất</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <?php
      $menuDashboard = $this->layout()->controller == "Admin\Controller\HomeController";
      $menuUser = $this->layout()->controller == "Admin\Controller\UserController";
      $menuGeneral = $menuDashboard || $menuUser;
      ?>
      <ul class="nav nav-primary">
        <li class="nav-item active">
          <a data-toggle="collapse" href="#general" class="collapsed" aria-expanded="<?=$menuGeneral ? 'true': 'false'?>">
            <i class="fas fa-layer-group"></i>
            <p>Quản trị chung</p>
            <span class="caret"></span>
          </a>
          <div class="collapse<?=$menuGeneral ? ' show': ''?>" id="general">
            <ul class="nav nav-collapse">
              <li<?=$menuDashboard ? ' class="active"' : ''?>>
                <a href="/admin"><i class="fas fa-home"></i> Bản tin chính</a>
              </li>
              <li<?=$menuUser ? ' class="active"' : ''?>>
                <a href="/admin/users"><i class="fas fa-users"></i> Quản lý người dùng</a>
              </li>
            </ul>
          </div>
        </li>
      </ul>

      <?php
      $menuCategory = $this->layout()->controller == "Admin\Controller\CategoryController";
      $menuProduct = $this->layout()->controller == "Admin\Controller\ProductController";
      $menuAdministration = $menuCategory || $menuProduct;
      ?>
      <ul class="nav nav-primary">
        <li class="nav-item active">
          <a data-toggle="collapse" href="#administration" class="collapsed" aria-expanded="<?=$menuAdministration ? 'true': 'false'?>">
            <i class="fas fa-cog fa-spin"></i>
            <p>Quản trị</p>
            <span class="caret"></span>
          </a>
          <div class="collapse<?=$menuAdministration ? ' show': ''?>" id="administration">
            <ul class="nav nav-collapse">
              <li<?=$menuCategory ? ' class="active"' : ''?>>
                <a href="/admin/categories"><i class="fas fa-th"></i> Loại sản phẩm</a>
              </li>
              <li<?=$menuProduct ? ' class="active"' : ''?>>
                <a href="/admin/products"><i class="fas fa-barcode"></i> Sản phẩm</a>
              </li>
            </ul>
          </div>
        </li>
      </ul>

    </div>
  </div>
</div>
