<div class="sidebar sidebar-style-2">
  <div class="sidebar-wrapper scrollbar scrollbar-inner">
    <div class="sidebar-content">
      <div class="user">
        <div class="avatar-sm float-left mr-2">
          <img src="https://ui-avatars.com/api/?name=<?=$this->layout()->loggedUser->full_name?>" alt="avatar" class="avatar-img rounded-circle">
        </div>
        <div class="info">
          <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
								<span>
                  <?=$this->layout()->loggedUser->full_name?>
                  <span class="user-level"><?=$this->layout()->loggedUser->role?></span>
									<span class="caret"></span>
								</span>
          </a>
          <div class="clearfix"></div>

          <div class="collapse in" id="collapseExample">
            <ul class="nav">
              <li>
                <a href="javascript:updateMyAccount();">
                  <span class="link-collapse">My Account</span>
                </a>
              </li>
              <li>
                <a href="/sign-out">
                  <span class="link-collapse">Logout</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <?php
      $menuDashboard = $this->currentRoute()->matchController('homecontroller');
      $menuUser = $this->currentRoute()->matchController('usercontroller');
      $menuReport = $this->currentRoute()->matchController('reportcontroller');
      $menuGeneral = $menuDashboard || $menuUser || $menuReport;
      ?>
      <ul class="nav nav-primary">
        <li class="nav-item active">
          <a data-toggle="collapse" href="#general" class="collapsed" aria-expanded="<?=$menuGeneral ? 'true': 'false'?>">
            <i class="fas fa-layer-group"></i>
            <p>General</p>
            <span class="caret"></span>
          </a>
          <div class="collapse<?=$menuGeneral ? ' show': ''?>" id="general">
            <ul class="nav nav-collapse">
              <li<?=$menuDashboard ? ' class="active"' : ''?>>
                <a href="/admin"><i class="fas fa-home"></i> Dashboard</a>
              </li>
              <li<?=$menuUser ? ' class="active"' : ''?>>
                <a href="/admin/users"><i class="fas fa-users"></i> Users</a>
              </li>
              <li<?=$menuReport ? ' class="active"' : ''?>>
                <a href="/admin/reports"><i class="fas fa-chart-bar"></i> Reports</a>
              </li>
            </ul>
          </div>
        </li>
      </ul>

      <?php
      $menuCategory = $this->currentRoute()->matchController('categorycontroller');
      $menuProduct = $this->currentRoute()->matchController('productcontroller');
      $menuAdministration = $menuCategory || $menuProduct;
      ?>
      <ul class="nav nav-primary">
        <li class="nav-item active">
          <a data-toggle="collapse" href="#administration" class="collapsed" aria-expanded="<?=$menuAdministration ? 'true': 'false'?>">
            <i class="fas fa-cog fa-spin"></i>
            <p>Administration</p>
            <span class="caret"></span>
          </a>
          <div class="collapse<?=$menuAdministration ? ' show': ''?>" id="administration">
            <ul class="nav nav-collapse">
              <li<?=$menuCategory ? ' class="active"' : ''?>>
                <a href="/admin/categories"><i class="fas fa-th"></i> Categories</a>
              </li>
              <li<?=$menuProduct ? ' class="active"' : ''?>>
                <a href="/admin/products"><i class="fas fa-barcode"></i> Products</a>
              </li>
            </ul>
          </div>
        </li>
      </ul>

    </div>
  </div>
</div>