<div class="modal-dialog modal-lg" role="document">
  <!--Content-->
  <div class="modal-content">
    <!--Header-->
    <div class="modal-header bg-blue text-white">
      <h3><?=(isset($this->myCategory)) ? "Cập nhật" : "Tạo"?> Loại sản phẩm</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <!--Body-->
    <div class="modal-body mb-0">
      <form id="formCategory" class="eventEnterKey" data-enterkey="btnSave" novalidate>
        <div class="row">
          <div class="form-group label-float col-md-5">
            <label for="kind" class="required">Lớp sản phẩm</label>
            <select class="form-control husSelect" id="kind" name="kind" required>
              <option value="" selected disabled>Chọn lớp sản phẩm</option>
              <option value="0"<?=isset($this->myCategory) && $this->myCategory->kind == 0 ? ' selected' : ''?>>iOS</option>
              <option value="1"<?=isset($this->myCategory) && $this->myCategory->kind == 1 ? ' selected' : ''?>>Android</option>
              <option value="2"<?=isset($this->myCategory) && $this->myCategory->kind == 2 ? ' selected' : ''?>>Phụ kiện điện thoại</option>
            </select>
          </div>
          <div class="form-group label-float col-md-7">
            <label for="name" class="required">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="<?=isset($this->myCategory) ? $this->myCategory->name : ''?>" required>
          </div>
          <div class="form-group label-float col-md-3">
            <label for="status">Status</label>
            <select class="form-control" id="status" name="status">
              <option value="0"<?=isset($this->myCategory) && $this->myCategory->status == 0 ? ' selected' : ''?>>INACTIVE</option>
              <option value="1"<?=isset($this->myCategory) && $this->myCategory->status == 1 ? ' selected' : ''?>>ACTIVE</option>
            </select>
          </div>
        </div>

        <input type="hidden" id="idRecord" name="idRecord" value="<?=isset($this->myCategory)? $this->myCategory->id : 0?>">
      </form>
    </div>

    <div class="modal-footer justify-content-center">
      <button id="btnSave" class="btn btn-primary"><span class="btn-label"><i class="fa fa-save"></i></span> <?=$this->layout()->translator->getLang('btn_save')?></button>
    </div>
  </div>
  <!--/.Content-->
</div>
