<div class="modal-dialog modal-lg" role="document">
  <!--Content-->
  <div class="modal-content">
    <!--Header-->
    <div class="modal-header bg-blue text-white">
      <h3><?=(isset($this->myCategory)) ? "Update" : "New"?> Category</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <!--Body-->
    <div class="modal-body mb-0">
      <form id="formCategory" class="eventEnterKey" data-enterkey="btnSave" novalidate>
        <div class="row">
          <div class="form-group label-float col-md-4d5">
            <label for="parentCategory" class="required">Parent Category</label>
            <select class="form-control husSelect" id="parentCategory" name="parentCategory">
              <option value="0">None</option>
            <?php foreach ($this->parentCategories as $parentCategory):?>
              <option value="<?=$parentCategory->id?>"<?=isset($this->myCategory) && $this->myCategory->parent_id == $parentCategory->id ? ' selected' : ''?>><?=$parentCategory->name?></option>
            <?php endforeach;?>
            </select>
          </div>
          <div class="form-group label-float col-md-4d5">
            <label for="name" class="required">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="<?=isset($this->myCategory) ? $this->myCategory->name : ''?>" required>
          </div>
          <div class="form-group label-float col-md-3">
            <label for="status">Status</label>
            <select class="form-control" id="status" name="status">
              <option value="INACTIVE"<?=isset($this->myCategory) && $this->myCategory->status == 'INACTIVE' ? ' selected' : ''?>>INACTIVE</option>
              <option value="ACTIVE"<?=isset($this->myCategory) && $this->myCategory->status == 'ACTIVE' ? ' selected' : ''?>>ACTIVE</option>
            </select>
          </div>
        </div>

        <input type="hidden" id="idRecord" name="idRecord" value="<?=isset($this->myCategory)? $this->myCategory->id : 0?>">
      </form>
    </div>

    <div class="modal-footer justify-content-center">
      <button id="btnSave" class="btn btn-primary"><span class="btn-label"><i class="fa fa-save"></i></span> <?=$this->layout()->translator->getLang('btn_save')?></button>
    </div>
  </div>
  <!--/.Content-->
</div>
