<table class="table table-striped table-hover">
<thead>
  <tr>
    <th width="39%" class="text-center">Parent Category</th>
    <th width="39%" class="text-left">Name</th>
    <th width="12%" class="text-center">Status</th>
    <th width="10%" class="text-center">Actions</th>
  </tr>
</thead>
<tbody>
<?php if (empty($this->categories)):?>
  <tr>
    <td colspan="4" class="text-center">No records</td>
  </tr>
<?php else:?>
  <?php foreach ($this->categories as $category):?>
    <tr>
      <td class="text-center"><?=$category->parentCategory?></td>
      <td class="text-left"><?=$category->name?></td>
      <td class="text-center"><?=$category->status?></td>
      <td class="text-center">
        <a href="javascript:editCategory(<?=$category->id?>);" title="<?=$this->layout()->translator->getLang('tooltip_edit')?>"><i class="fas fa-pencil-alt text-blue"></i></a>
        &nbsp;
        <a href="javascript:deleteCategory(<?=$category->id?>);" title="<?=$this->layout()->translator->getLang('tooltip_delete')?>"><i class="far fa-trash-alt text-red"></i></a>
      </td>
    </tr>
  <?php endforeach;?>
<?php endif;?>
</tbody>
</table>

<?php
if (isset($this->paginator) && $this->paginator->getTotalItemCount() > $this->paginator->getItemCountPerPage()):
  $from = ($this->paginator->getCurrentPageNumber() - 1)*$this->paginator->getItemCountPerPage() + 1;
  $to = $this->paginator->getCurrentPageNumber()*$this->paginator->getItemCountPerPage();
  if ($to > $this->paginator->getTotalItemCount()) {
    $to = $this->paginator->getTotalItemCount();
  }
?>
  <!--Paginator-->
  <div class="paginator">
    <div class="float-left text-blue">
      <?=$from?> - <?=$to?> of <?=$this->paginator->getTotalItemCount()?>
    </div>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', ['route' => '/', 'ajaxFunc' => 'getCategories']) ?>
  </div>
<?php endif; ?>