<table class="table table-striped table-hover">
<thead>
  <tr>
    <th width="20%" class="text-center">ID</th>
    <th width="80%" class="text-left">Nick Name</th>
  </tr>
</thead>
<tbody>
<?php if (empty($this->users)):?>
  <tr>
    <td colspan="2" class="text-center">No records</td>
  </tr>
<?php else:?>
  <?php foreach ($this->users as $user):?>
    <tr>
      <td class="text-center"><?=$user->id?></td>
      <td><?=$user->nick_name?></td>
    </tr>
  <?php endforeach;?>
<?php endif;?>
</tbody>
</table>

<!--Paginator-->
<?php
if (isset($this->paginator) && $this->paginator->getTotalItemCount() > $this->paginator->getItemCountPerPage()):
  $from = ($this->paginator->getCurrentPageNumber() - 1)*$this->paginator->getItemCountPerPage() + 1;
  $to = $this->paginator->getCurrentPageNumber()*$this->paginator->getItemCountPerPage();
  if ($to > $this->paginator->getTotalItemCount()) {
    $to = $this->paginator->getTotalItemCount();
  }
  ?>
  <div class="paginator">
    <div class="float-left text-blue">
      <?=$from?> - <?=$to?> of <?=$this->paginator->getTotalItemCount()?>
    </div>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', ['route' => '/', 'ajaxFunc' => 'getUsers']) ?>
  </div>

<?php endif; ?>
</div>