<table class="table table-striped table-hover">
<thead>
  <tr>
    <th width="16%" class="text-left">Loại sản phẩm</th>
    <th width="15%" class="text-center">Hình ảnh</th>
    <th width="20%" class="text-left">Tên sản phẩm</th>
    <th width="13%" class="text-center">Hãng</th>
    <th width="15%" class="text-right">Gíá</th>
    <th width="11%" class="text-center">Nổi bật</th>
    <th width="10%" class="text-center">Actions</th>
  </tr>
</thead>
<tbody>
<?php if (empty($this->products)):?>
  <tr>
    <td colspan="7" class="text-center">Không có sản phẩm nào.</td>
  </tr>
<?php else:?>
  <?php foreach ($this->products as $product):?>
    <tr>
      <td class="text-left"><?=$product->categoryName?></td>
      <td class="text-center"><img width="100" height="100" src="<?=$product->image?>" alt="<?=$product->name?>"></td>
      <td class="text-left"><?=$product->name?></td>
      <td class="text-center"><?=$product->branch?></td>
      <td class="text-right"><?=formatNumber($product->price)?></td>
      <td class="text-center"><?=$product->is_feature ? '<i class="fa fa-check text-green"></i>' : ''?></td>
      <td class="text-center">
        <a href="javascript:editProduct(<?=$product->id?>);" title="<?=$this->layout()->translator->getLang('tooltip_edit')?>"><i class="fas fa-pencil-alt text-blue"></i></a>
        &nbsp;
        <a href="javascript:deleteProduct(<?=$product->id?>);" title="<?=$this->layout()->translator->getLang('tooltip_delete')?>"><i class="far fa-trash-alt text-red"></i></a>
      </td>
    </tr>
  <?php endforeach;?>
<?php endif;?>
</tbody>
</table>

<?php
if (isset($this->paginator) && $this->paginator->getTotalItemCount() > $this->paginator->getItemCountPerPage()):
  $from = ($this->paginator->getCurrentPageNumber() - 1)*$this->paginator->getItemCountPerPage() + 1;
  $to = $this->paginator->getCurrentPageNumber()*$this->paginator->getItemCountPerPage();
  if ($to > $this->paginator->getTotalItemCount()) {
    $to = $this->paginator->getTotalItemCount();
  }
?>
  <!--Paginator-->
  <div class="paginator">
    <div class="float-left text-blue">
      <?=$from?> - <?=$to?> of <?=$this->paginator->getTotalItemCount()?>
    </div>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', ['route' => '/', 'ajaxFunc' => 'getProducts']) ?>
  </div>
<?php endif; ?>
