<!-- HERO SLIDER SECTION-->
<section class="text-white bg-cover bg-center primary-overlay overlay-dense" style="background: url('img/photogrid.jpg') repeat">
  <div class="overlay-content py-5">
    <div class="container py-4">
      <!-- Hero slider-->
      <div class="swiper-container homepage-slider">
        <div class="swiper-wrapper">
          <!-- Hero Slide-->
        <?php if (!empty($this->featuredProducts)):?>
          <?php foreach($this->featuredProducts as $product):?>
          <div class="swiper-slide h-auto mb-5">
              <div class="row gy-5 h-100 align-items-center">
                <div class="col-lg-7"><img class="img-fluid" width="400" height="200" src="<?=$product->image?>" alt="<?=$product->name?>"></div>
                <div class="col-lg-5">
                  <h1 class="text-uppercase"><?=$product->name?></h1>
                  <ul class="list-unstyled text-uppercase fw-bold mb-0">
                    <li class="mb-2">Giá: <?=formatNumber($product->price)?> VND</li>
                    <li class="mb-2">Hãng: <?=$product->branch_name?></li>
                    <li>Nhanh tay kẻo hết</li>
                  </ul>
                </div>
              </div>
            </div>
          <?php endforeach;?>
        <?php endif;?>
        <div class="swiper-pagination swiper-pagination-light"></div>
      </div>
    </div>
  </div>
</section>

<!-- SAN PHAM NOI BAT SECTION-->
<section class="py-5">
  <div class="container py-4">
    <header class="mb-5">
      <h2 class="lined lined-center text-uppercase mb-4">Sản phẩm nổi bật</h2>
    </header>
    <div class="row gy-5">
      <!-- product box-->
      <?php if (empty($this->featuredProducts)):?>
        <div class="col-lg-12 col-md-12">Không có sản phẩm</div>
      <?php else:?>
        <?php foreach($this->featuredProducts as $product):?>
          <div class="col-lg-3 col-md-6">
            <div class="box-image">
              <div class="mb-4 primary-overlay"><img class="img-fluid" src="<?=$product->image?>" alt="<?=$product->name?>">
                <div class="overlay-content d-flex flex-column justify-content-center p-4">
                  <ul class="list-inline mb-0 box-image-content text-center">
                    <li class="list-inline-item"><a class="btn btn-outline-light" href="/products/<?=$product->id?>"> <i class="fas fa-link me-2"></i>Chi tiết</a></li>
                  </ul>
                </div>
              </div>
              <div class="text-center">
                <h3 class="h4 text-uppercase text-primary"> <a class="text-reset" href="/products/<?=$product->id?>"><?=$product->name?></a></h3>
                <p class="small text-uppercase text-muted">Giá: <?=formatNumber($product->price)?> VND</p>

                <a class="btn btn-outline-primary" href="/products/<?=$product->id?>">Mua ngay</a>
              </div>
            </div>
          </div>
        <?php endforeach;?>
      <?php endif;?>
    </div>
  </div>
</section>

<!-- SAN PHAM XEM NHIEU SECTION-->
<section class="py-5">
  <div class="container py-4">
    <header class="mb-5">
      <h2 class="lined lined-center text-uppercase mb-4">Sản phẩm xem nhiều nhất</h2>
    </header>
    <div class="row gy-5">
      <!-- product box-->
      <?php if (empty($this->mostViewedProducts)):?>
        <div class="col-lg-12 col-md-12">Không có sản phẩm</div>
      <?php else:?>
        <?php foreach($this->mostViewedProducts as $product):?>
          <div class="col-lg-3 col-md-6">
          <div class="box-image">
            <div class="mb-4 primary-overlay"><img class="img-fluid" src="<?=$product->image?>" alt="<?=$product->name?>">
              <div class="overlay-content d-flex flex-column justify-content-center p-4">
                <ul class="list-inline mb-0 box-image-content text-center">
                  <li class="list-inline-item"><a class="btn btn-outline-light" href="/products/<?=$product->id?>"> <i class="fas fa-link me-2"></i>Chi tiết</a></li>
                </ul>
              </div>
            </div>
            <div class="text-center">
              <h3 class="h4 text-uppercase text-primary"> <a class="text-reset" href="/products/<?=$product->id?>"><?=$product->name?></a></h3>
              <p class="small text-uppercase text-muted">Giá: <?=formatNumber($product->price)?> VND</p>

              <a class="btn btn-outline-primary" href="/products/<?=$product->id?>">Mua ngay</a>
            </div>
          </div>
        </div>
        <?php endforeach;?>
      <?php endif;?>
    </div>
  </div>
</section>
