<div class="modal-dialog modal-lg" role="document">
  <!--Content-->
  <div class="modal-content">

    <!--Header-->
    <div class="modal-header bg-blue text-white">
      <h4>Đăng ký Tài khoản</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <!--Body-->
    <div class="modal-body mb-0">

      <form id="formRegister" class="eventEnterKey" data-enterkey="btnRegister" novalidate>
        <div class="row">
          <div class="form-group label-float col-md-6">
            <label for="email" class="required">Email</label>
            <input type="text" id="email" name="email" class="form-control" required autofocus>
            <div class="invalid-feedback">Sai email</div>
          </div>
          <div class="form-group label-float col-md-6">
            <label for="fullName" class="required">Họ và tên</label>
            <input type="text" id="fullName" name="fullName" class="form-control" required>
            <div class="invalid-feedback">Sai họ và tên</div>
          </div>
        </div>
        <div class="row">
          <div class="form-group label-float col-md-4">
            <label for="password" class="required">Mật khẩu</label>
            <input type="password" id="password" name="password" class="form-control" placeholder="Nhập mật khẩu" required>
          </div>
          <div class="form-group label-float col-md-4">
            <label for="confirmPassword">Xác nhận mật khẩu</label>
            <input type="password" id="confirmPassword" name="confirmPassword" class="form-control">
          </div>
          <div class="form-group label-float col-md-4">
            <label for="mobile">Điện thoại</label>
            <input type="text" id="mobile" name="mobile" class="form-control">
          </div>
        </div>
        <div class="row">
            <div class="form-group label-float col-md-12">
              <label for="address">Địa chỉ</label>
              <input type="text" id="address" name="address" class="form-control">
            </div>
        </div>
        <input type="hidden" id="reCaptchaToken" name="reCaptchaToken">
      </form>
    </div>
    <div class="modal-footer justify-content-center">
      <button id="btnRegister" class="btn btn-primary"><span class="btn-label"><i class="fa fa-save"></i></span> <?=$this->layout()->translator->getLang('btn_sign_up')?></button>
    </div>
  </div>
  <!--/.Content-->
</div>
